name: Increment Tag

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Version part to increment (major, minor, patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  add-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get-latest-tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null)
          if [[ "$LATEST_TAG" == "" ]]; then
            echo "Error: No tags found."
            exit 1
          fi
          echo "Latest tag: $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Increment version
        id: increment-version
        run: |
          LATEST_TAG=${{ steps.get-latest-tag.outputs.latest_tag }}
          INCREMENT_TYPE=${{ github.event.inputs.increment }}

          VERSION=${LATEST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          # Increment the appropriate part
          if [ "$INCREMENT_TYPE" == "major" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [ "$INCREMENT_TYPE" == "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          echo "New tag: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          NEW_TAG=${{ steps.increment-version.outputs.new_tag }}
          git tag -a $NEW_TAG -m "Release $NEW_TAG"
          git push origin $NEW_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
