name: Daily PR

on:
  # Run daily
  schedule:
    - cron: "0 0 * * *"
  # For manual triggering
  workflow_dispatch:

jobs:
  update-models:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_OIDC_ROLE_NAME }}
          aws-region: us-east-1

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Update models.yaml
        run: ./list_models.sh

      - name: Check for changes
        id: check-changes
        run: |
          git diff --exit-code assets/models.yaml || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update Bedrock model list"
          title: "chore: update Bedrock model list"
          body: |
            This PR updates the list of available Bedrock models.

            Auto-generated by GitHub Actions.
          branch: update-bedrock-models
          base: main
          delete-branch: true
